graph TD
    %% Sources de données
    WS((waterSource$))
    WEA((weatherSource$))
    GM((glacierMelt$))
    WW((wastewaterSource$))
    UC((userConsumptionSource$))

    %% Composables et services
    WS --> |subscribe| IA[inflowAggregator]
    WEA --> |subscribe| IA
    GM --> |subscribe| IA

    IA --> |emit| AI{aggregatedInflow$}
    AI --> |subscribe| UWS[useWaterSystem]

    WEA --> |subscribe| UWS[useWaterSystem]
    UWS --> |emit| SS{systemState$}

    WEA --> |subscribe| UWS[useWeatherStation]
    UWS --> |emit| WD{weatherData$}

    %% Composants
    SS --> |subscribe| WSD[WaterSystemDashboard]
    WD --> |subscribe| MWS[MainWeatherStationComponent]

    %% Légende
    classDef observable fill:#f9f,stroke:#333,stroke-width:2px;
    classDef subject fill:#bbf,stroke:#333,stroke-width:2px;
    classDef component fill:#dfd,stroke:#333,stroke-width:2px;

    class WS,WEA,GM,WW,UC observable;
    class AI,SS,WD subject;
    class WSD,MWS component;